#!/bin/sh

PREREQ=""
DESCRIPTION="SlimbookOS autologin settings..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# GDM
GDMCustomFile=/root/etc/gdm3/custom.conf
if [ -f $GDMCustomFile ]; then
    sed -i -r \
        -e "s/^#[ ]*AutomaticLoginEnable =.*\$/AutomaticLoginEnable=true/" \
        -e "s/^#[ ]*AutomaticLogin =.*\$/AutomaticLogin=$USERNAME/" \
	-e "s/^#[ ]*TimedLoginEnable =.*\$/TimedLoginEnable=false/" \
        -e "s/^#[ ]*WaylandEnable=false\$/WaylandEnable=true/" \
        $GDMCustomFile
fi

# SDDM
if [ -f /root/usr/bin/sddm ]; then
       sddm_session=plasma.desktop

    cat >>/root/etc/sddm.conf <<EOF
[Autologin]
User=$USERNAME
Session=$sddm_session
EOF
fi

log_end_msg
