#!/bin/sh

PREREQ=""
DESCRIPTION="SlimbookOS disable kwallet"

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

#At this point, home dir already exists
mkdir -p /root/home/$USERNAME/.config
    cat >>/root/home/$USERNAME/.config/kwalletrc <<EOF
[Wallet]
Enabled=false
EOF

log_end_msg
